version: '3'

services:
  mlflow:
    build: .
    ports:
      - 5000:5000
    volumes:
      - "./data:/mlflow"
      - ~/.google/credentials/:/.google/credentials
    environment:
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_PRIVATE_IP: '${DB_PRIVATE_IP}'
      DB_NAME: '${DB_NAME}'
      BUCKET_NAME: '${BUCKET_NAME}'
      GOOGLE_APPLICATION_CREDENTIALS: /.google/credentials/google_credentials.json
